# Generated by Django 5.0.3 on 2024-07-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='c',
            new_name='description',
        ),
    ]
