# Generated by Django 5.0.3 on 2024-07-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_trainer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='image',
            new_name='for_image_trainer',
        ),
    ]
