# Generated by Django 5.0.3 on 2024-07-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('image_for_classes', models.ImageField(blank=True, null=True, upload_to='classes_media/')),
            ],
        ),
        migrations.CreateModel(
            name='BoxingCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='CardioCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('intensity_level', models.CharField(max_length=100)),
                ('equipment_needed', models.CharField(max_length=100)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='CyclingCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('terrain_type', models.CharField(max_length=100)),
                ('bike_type', models.CharField(max_length=100)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='KarateCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('belt_colors', models.CharField(max_length=100)),
                ('kata_required', models.BooleanField(default=True)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='MeditationCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('meditation_style', models.CharField(max_length=100)),
                ('relaxation_techniques', models.CharField(max_length=100)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
