# Generated by Django 5.0.3 on 2024-06-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxingcourse',
            name='punch_types',
        ),
        migrations.RemoveField(
            model_name='boxingcourse',
            name='sparring_partner_required',
        ),
    ]
