# Generated by Django 5.0.3 on 2024-07-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_boxingcourse_punch_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='image_cousrse',
        ),
    ]
