# Generated by Django 5.0.3 on 2024-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_image_course_image_cousrse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_cousrse',
        ),
        migrations.AddField(
            model_name='course',
            name='image_for_classes',
            field=models.ImageField(blank=True, null=True, upload_to='classes_media/'),
        ),
    ]
