# Generated by Django 5.0.3 on 2024-07-19 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
        ('products', '0002_rename_c_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_cart', to='basket.basket', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='products.product', verbose_name='Продукт'),
        ),
    ]
