# Generated by Django 5.0.3 on 2024-07-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        ('trainer', '0006_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trainer.trainer', verbose_name='Тренер'),
        ),
    ]
